### ISSUE TITLE
[PE-D][Tester B] User guide does not have information on website parameter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-2/tp#210] opened 2023-03-31 19:57 UTC
The example command shown has a website parameter `w/www.google.com`. This is also a required parameter when adding a new role in the product. However, it is not shown in the list of parameters.

Adding it into the list of parameters would make it more clear for readers.

![image.png](https://raw.githubusercontent.com/LeonardYam/ped/main/files/0dbc75f5-eb62-4ea3-aef8-6f889cc61a15.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: LeonardYam/ped#5

**Comment by RyanQiu1** [comment] 2023-04-01 02:38
Fixed

**Comment by dsja612** [comment] 2023-04-05 06:32
duplicate of #185

**Closed by dsja612** 2023-04-05 06:32 UTC
Labels: documentation, type.DocumentationBug, good to fix
